// @ts-check

/**
 * The sidebar is autogenerated from the docs/ folder, ordered by each file's
 * `sidebar_position` frontmatter — so a page added in Dhub's visual editor appears in the
 * sidebar with no change to this file. That is deliberate: a CMS that required an engineer to
 * edit JavaScript for every new page would defeat the point of the exercise.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
